defaults:
  - _self_

# 全局默认参数
model: gpt-4o
db_mode: simple
parent_slots: 4
child_slots: 8
n_init: 40
budget: 200
seed: 0
capacity: 40
init_pop_path: null

# 各任务专属参数
tasks:
  tsp:
    n_init: 60
    parent_slots: 6
    child_slots: 12
    # 其他tsp专属参数
  kernelopt:
    n_init: 30
    parent_slots: 3
    child_slots: 6
    # 其他kernelopt专属参数
  gcolor:
    n_init: 50
    parent_slots: 5
    child_slots: 10
    # 其他gcolor专属参数
  promptopt:
    
