defaults:
  - _self_


# =========================
# 全局默认参数
# =========================
# model: 
#   - openai/gpt-4o
#   - openai/gpt-4o-mini
#   - openai/gpt-3.5-turbo
#   - openai/o1-mini
#   - vertex_ai/gemini-1.5
#   - vertex_ai/claude3.5-sonnet-v2
#   - vertex_ai/mistral-large
#   - vertex_ai/gemini-1.5-flash
#   - llama3.1-8b
#   - meta-llama/llama-3.3-70b-instruct:free
#   - deepseek/deepseek-r1-0528:free
#   - deepseek/deepseek-r1-0528-qwen3-8b:free
#   - deepseek/deepseek-r1-distill-qwen-7b
#   - deepseek/deepseek-chat-v3-0324:free
#   - mistralai/mistral-small-3.2-24b-instruct:free
#   - mistralai/magistral-small-2506
#   - mistralai/mistral-7b-instruct-v0.3
#   - minimax/minimax-m1
#   - qwen/qwen3-30b-a3b-04-28:free
#   - qwen/qwen3-14b:free
#   - qwen/qwen3-8b-04-28:free
#   - qwen/qwen3-32b-04-28:free
#   - qwen/qwen3-235b-a22b:free
#   - x-ai/grok-3-mini-beta
#   - meta-llama/llama-4-scout:free
#   - meta-llama/llama-3.1-70b-instruct
#   - meta-llama/llama-3.1-8b-instruct
#   - meta-llama/llama-3.2-3b-instruct
#   - google/gemma-3n-e4b-it


# db_mode: [simple, map]
# task: [tsp, gcolor, promptopt, codegen, kernelopt]
# parent_slots: int
# child_slots: int
# n_init: int
# budget: int
# seed: int
# capacity: int
# init_pop_path: str or null
# enable_zero_shot_eval: bool

task: tsp
model: openai/gpt-4o-mini
db_mode: simple
parent_slots: 3
child_slots: 10
n_init: 40
budget: 300
seed: 21
capacity: 40
init_pop_path: null
enable_zero_shot_eval: false

# For task-specific options:
# tsp:
# kernelopt:

tasks:
  tsp:
    city_num: 30
    n_init: 40
    parent_slots: 3
    child_slots: 10
    # 其他tsp专属参数
  kernelopt:
    n_init: 2
    parent_slots: 1
    child_slots: 1
    capacity: 2
    # 其他kernelopt专属参数
  gcolor:
    n_init: 50
    parent_slots: 5
    child_slots: 10
    # 其他gcolor专属参数
  promptopt:
    n_init: 10
    parent_slots: 2
    child_slots: 5
    budget: 150
    eval_task: sum   # sum: summarization, sim: simplification
    eval_set: test
    # 其他promptopt专属参数
  symboreg_oscillator1:
    seed: 21
  symboreg_oscillator2:
    seed: 21
    # 其他可选参数

