models:
  - gpt-4o-mini
  - gpt-4o-2024-11-20
  - gpt4-turbo
  - o1-mini-2024-09-12
  - openai/gpt-4o-mini
  - openai/gpt-4.1-mini
  - openai/gpt-4.1-nano
  - openai/gpt-4.1
  - openai/gpt-4o
  - openai/gpt-3.5-turbo
  - openai/o1-mini
  - vertex_ai/mistral-large
  - vertex_ai/gemini-1.5-flash
  - vertex_ai/gemini-2.0-flash
  - vertex_ai/gemini-1.0
  - vertex_ai/gemini-1.5
  - vertex_ai/claude3.5-sonnet-v2
  - vertex_ai/gemini-2.0-flash
  - Qwen/Qwen3-8B
  - Qwen/Qwen3-30B-A3B
  - Qwen/Qwen3-0.6B
  - Qwen/Qwen3-1.7B
  - Qwen/Qwen3-4B
  - Qwen/Qwen3-14B

tasks:
  - tsp
  - gcolor
  - promptopt
  - codegen


db_mode:
  - simple
  - map
# ↓ 下面两个顶层字段只是"默认"，真正 sweep 用 shell 循环
seeds: [0,1,2,3,4,5,6,7]     # 最大 seed，脚本只做 sanity check
calls_budget: 200

ga_params:
  llm_max_tokens: 163840
  parent_slots: 4
  child_slots: 8
  num_init: 40
